# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/react/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/API/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/API.Tests/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/DataFacade/" # Location of package manifests
    schedule:
      interval: "monthly"      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/DataFacade.Tests/" # Location of package manifests
    schedule:
      interval: "monthly"      
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/src/API/"        # Dockerfile(s) in API folder
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/src/react/"      # Dockerfile(s) in react folder (if present)
    schedule:
      interval: "monthly"
      
